[package]
name = "integration_station"
version = "0.1.0"
authors = ["Hunter Mellema <mellemahp@gmail.com>"]
edition = "2018"


[dependencies]
nalgebra = "0.19.0"
lazy_static = "1.4.0"

[dev-dependencies]
itertools-num = '0.1'
